### ISSUE TITLE
Maybe unlocked fps on web?

### ISSUE THREAD

**Issue by lenscas** [jayrave/runner#1]
Just a heads up, when looking through the code I found a comment about not needing to limit the draw rate (https://github.com/jayrave/runner/blob/master/quicksilver_frontend/src/main.rs#L48 )

This is something else than I experienced. In web builds I was able to influence the fps by changing the amount of events I gave, which didn't happen in native builds. The issue https://github.com/ryanisaacg/quicksilver/issues/580 seems to agree with what I noticed.

It could be that the fix for https://github.com/rust-windowing/winit/issues/1493 is the cause of this change in behavior though. In which case, the frame rate depends on how often the callback to `requestAnimationFrame` gets called by the browser, which seems to depend on the refresh rate of the monitor.

**Comment by jayrave** [comment]
Yikes! Just happened to look at this issue since the notifications for this got a bit buried in my inbox. Sorry about that.

It is pretty interesting. I didn't know that `requestAnimationFrame` is dependent on the refresh rate of the monitor (which does make a lot of sense when thinking about it). Essentially, I put in the [`FrameLimiter`](https://github.com/jayrave/runner/blob/4fa174c1cf502b8db2d9945941eb274fb170af85/sdl2_frontend/src/frame_limiter.rs) for the [`sdl`](https://github.com/jayrave/runner/blob/4fa174c1cf502b8db2d9945941eb274fb170af85/sdl2_frontend/src/main.rs#L84) frontend to make sure that I don't end up painting too often & lead to in-efficient usage of CPU & battery. If `requestAnimationFrame` is going to be based on the refresh rate of the monitor, it shouldn't be a big issue I believe. 

Anything more than 60 FPS for this game would be a bit of a waste (physics update speed is not tied to this rate but is instead capped to 60 times per second using [`GamePlay`](https://github.com/jayrave/runner/blob/4fa174c1cf502b8db2d9945941eb274fb170af85/core/src/resources/game_play.rs)) but I think it isn't too concerning because of the sane screen refresh rates we have out there.

I'll update the comment in the code to reflect this if this sounds fair

**Comment by jayrave** [comment]
Great! Updated the comment accordingly  => https://github.com/jayrave/runner/blob/b087ef58df0af06cfbb93a40fe9acbaf6b75bbc5/quicksilver_frontend/src/main.rs#L48
